# https://github.com/aws-actions/amazon-ecr-login#login-to-amazon-ecr-public-then-build-and-push-a-docker-image
name: build & push docker image to AWS ECR

on:
  push:
    branches: [ "main", "rora" ]
  pull_request:
    branches: [ "main", "rora" ]
  
env:
  #ecr_url: "arn:aws:ecr:ap-northeast-2:644329934495:repository/*"
  role_arn: "arn:aws:iam::644329934495:role/ecr-github-action-oidc-role"
  aws_region: "ap-northeast-2"
  repository: "ohrory218"
  #image_tag: ${{ github.sha }}
  image_name: "helloworld"
  image_tag: "1.1"
  ecr_image_tag: 

jobs:
  build_and_push_ecs: # job 고유 식별자
    name: "# AWS ECR 로그인"
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: "1. github runner에 레파지토리 체크아웃"
        uses: actions/checkout@v3

      # Before each of the following examples, make sure to include the following:
      - name: "2. AWS credential 설정"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.aws_region }}
          role-session-name: GitHubActions
          role-to-assume: ${{ env.role_arn }}

      # Login to Amazon ECR Private, then build and push a Docker image: (cf. public)
      - name: "3. AMAZON ECR 로그인"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #https://github.com/docker/metadata-action
      - name: "4. 도커 이미지에 메타 데이터 만들기"
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.repository }}/${{ env.image_name }}
      
      # https://github.com/docker/build-push-action
      - name: "5. 도커 이미지 Build"
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          # 1번 스텝의 id: meta에서 만들어진 outputs 객체의 tags, labels
          tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
      - name: "6. AMAZON ECR에 도커 이미지 PUSH"
        run: |
          docker tag ${{ env.repository }}/${{ env.image_name }} ${{ steps.login-ecr.outputs.registry }}/${{ env.repository }}:${{ env.aws_image_tag }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.repository }}:${{ env.aws_image_tag }}
